[package]
name = "fuzz-mp4-rust"
version = "0.1.0"
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
honggfuzz = "0.5.55"
serde_json = "1.0.96"

[dependencies.mp4]
path = ".."

[workspace]
members = ["."]

[[bin]]
name = "fuzz_mp4"
path = "fuzz_targets/fuzz_mp4.rs"